### ISSUE TITLE
error while requesting

### ISSUE THREAD

**Issue by odysseusmax** [encode/requests-async#39]
While making a head request the following errors occoured.

code used:
```
r = await requests.headt(url, allow_redirects=True)
```

error:
```
Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/adapters.py", line 53, in send
     timeout=timeout,
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/pool.py", line 77, in request
     connection = await self.acquire_connection(parsed_url, ssl=ssl, timeout=timeout)
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/pool.py", line 102, in acquire_connection
     ssl_context = await self.get_ssl_context(url, ssl)
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/pool.py", line 150, in get_ssl_context
     None, self.get_ssl_context_verify
  File "/app/.heroku/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
     result = self.fn(*self.args, **self.kwargs)
 TypeError: get_ssl_context_verify() missing 1 required positional argument: 'config'
 
 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/app/downlods.py", line 94, in direct_link
     r = await requests.head(url, allow_redirects=True)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/api.py", line 21, in head
     return await request("head", url, **kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/api.py", line 6, in request
     return await session.request(method=method, url=url, **kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/sessions.py", line 79, in request
     resp = await self.send(prep, **send_kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/sessions.py", line 136, in send
     r = await adapter.send(request, **kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/adapters.py", line 55, in send
    except (httpcore.BadRequest, socket.error) as err:
 AttributeError: module 'httpcore' has no attribute 'BadRequest'
```
pythn-3.7.3
requests-async-0.3.1

**Comment by lovelydinosaur** [comment]
Thanks for raising this.
I've just pushed a new release of the `httpcore` dependency that'll resolve this.

`pip install -U httpcore`  and check you've got 0.1.1 installed.

**Comment by odysseusmax** [comment]
Nop, remains the same.

Re-installed `requests-async`, verified `httpcore-0.1.1`, ` requests-async-0.3.1`

URL used: `https://nl21.seedr.cc/ff_get/446372158/The.Flash.2014.S05E18.Godspeed.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv?st=hJNSROlzq8soqcUsS1S4Sw&e=1555607511`.
 Happens only with some urls, this is one of them.


when `verify=False` was added as argument, issue gets solved but when `timeout` is set ,say `timeout=10`, this error arises again. `allow_redirect=True` does not seems to work
```
Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/adapters.py", line 53, in send
     timeout=timeout,
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/pool.py", line 77, in request
     connection = await self.acquire_connection(parsed_url, ssl=ssl, timeout=timeout)
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/pool.py", line 102, in acquire_connection
     ssl_context = await self.get_ssl_context(url, ssl)
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/pool.py", line 150, in get_ssl_context
     None, self.get_ssl_context_verify
   File "/app/.heroku/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
     result = self.fn(*self.args, **self.kwargs)
 TypeError: get_ssl_context_verify() missing 1 required positional argument: 'config'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/app/downlods.py", line 94, in direct_link
     r = await requests.head(url, allow_redirects=True)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/api.py", line 21, in head
     return await request("head", url, **kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/api.py", line 6, in request
     return await session.request(method=method, url=url, **kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/sessions.py", line 79, in request
     resp = await self.send(prep, **send_kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/sessions.py", line 136, in send
     r = await adapter.send(request, **kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/adapters.py", line 55, in send
     except (httpcore.BadRequest, socket.error) as err:
 AttributeError: module 'httpcore' has no attribute 'BadRequest'
 (False, AttributeError("module 'httpcore' has no attribute 'BadRequest'"))

```

**Comment by lovelydinosaur** [comment]
Right - apologies - few teething issues with the switch to `httpcore`, which allows us to get streaming requests/responses, connection pooling, etc...

I've release requests-async 0.4, which should resolve this issue properly now.
