### ISSUE TITLE
 'NoneType' object has no attribute 'resume_reading'

### ISSUE THREAD

**Issue by odysseusmax** [encode/requests-async#42]
Resently this happens. 
```
Traceback (most recent call last):
   File "/app/downlods.py", line 193, in direct_link
     async for chunk in rg.iter_content(chunk_size=8*1024):
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/models.py", line 60, in iter_content
     async for chunk in generate():
   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/models.py", line 46, in generate
     async for part in stream():
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/datastructures.py", line 184, in stream
     async for chunk in self.raw():
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/datastructures.py", line 197, in raw
     async for part in self.body_aiter:
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/connections.py", line 83, in _body_iter
     event = await self._receive_event()
   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/connections.py", line 100, in _receive_event
     self.reader.read(2048), self.timeout.read_timeout
   File "/app/.heroku/python/lib/python3.7/asyncio/tasks.py", line 388, in 
     return await fut
   File "/app/.heroku/python/lib/python3.7/asyncio/streams.py", line 646, in read
     self._maybe_resume_transport()
   File "/app/.heroku/python/lib/python3.7/asyncio/streams.py", line 417, in _maybe_resume_transport
     self._transport.resume_reading()
   File "/app/.heroku/python/lib/python3.7/asyncio/sslproto.py", line 345, in resume_reading
     self._ssl_protocol._transport.resume_reading()
 AttributeError: 'NoneType' object has no attribute 'resume_reading'
```

Link: `https://transfer.sh/5PNkN/MaxStudio_June.mkv `

code:

```
r = await requests.get(url, allow_redirects=True, stream=True, verify=False)
if(r.status_code < 400):
    async with aiofiles.open(filename, mode='wb') as fd:
            async for chunk in rg.iter_content(chunk_size=8*1024):
                 await fd.write(chunk)
```

**Comment by lovelydinosaur** [comment]
Is this occuring reliably or sporadically?
How can I reproduce the error?

**Comment by odysseusmax** [comment]
This happens with some links occasionally while downloading, original post updated with the link i used.

**Comment by lovelydinosaur** [comment]
Not able to replicate against latest versions.
Try updating to `requests-async` 0.6, and let me know if you've any continuing issues.

```python
import asyncio
import requests_async


async def async_get():
    url = "https://transfer.sh/5PNkN/MaxStudio_June.mkv"
    print('sending request')
    r = await requests_async.get(url, allow_redirects=True, stream=True, verify=False)
    print('got response')
    async for chunk in r.iter_content(chunk_size=8*1024):
         print('read %d bytes' % len(chunk))

loop = asyncio.get_event_loop()
loop.run_until_complete(async_get())
```

Output:

```shell
$ python ./example.py 
sending request
got response
read 10 bytes
```
