### ISSUE TITLE
name 'socket' is not defined

### ISSUE THREAD

**Issue by odysseusmax** [encode/requests-async#46]
**Link used:**
 `https://download.wetransfer.com//eu2/1d747c5c7b436407f3f886c67932b76120190505211938/3898f2ea5e14f176a27b9950281ee964ef593674/Mortal%20Engines%202018%20Hindi%20ORG%20Dual%20Audio%20www.downloadhub.ind.in%20720p%20BluRay%20ESubs.mkv?cf=y&token=eyJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWUiOiIxZDc0N2M1YzdiNDM2NDA3ZjNmODg2YzY3OTMyYjc2MTIwMTkwNTA1MjExOTM4IiwiZmlsZW5hbWUiOiJNb3J0YWwlMjBFbmdpbmVzJTIwMjAxOCUyMEhpbmRpJTIwT1JHJTIwRHVhbCUyMEF1ZGlvJTIwd3d3LmRvd25sb2FkaHViLmluZC5pbiUyMDcyMHAlMjBCbHVSYXklMjBFU3Vicy5ta3YiLCJleHBpcmVzIjoxNTU3MTI1ODM5LCJob3QiOmZhbHNlLCJieXRlc19lc3RpbWF0ZWQiOjEyNDE2MTcyNDksImVudHJpZXNfZmluZ2VycHJpbnQiOiIzODk4ZjJlYTVlMTRmMTc2YTI3Yjk5NTAyODFlZTk2NGVmNTkzNjc0Iiwid2F5YmlsbF91cmwiOiJodHRwOi8vcHJvZHVjdGlvbi5iYWNrZW5kLnNlcnZpY2UuZXUtd2VzdC0xLnd0OjkyOTIvd2F5YmlsbC92MS81NDJmZjA1NWU2NmY3YTE4ZTc0NGU4MjZjOThjZDlkMjdmZDhhNjJjMmFiYWI1NDQ5MGJiOTlmZTgxNmVhMjk3ODEwMjkwMTFhNGFmMTgxMGM0MmNiYzQ2OWY1YWFhMzA1NjM5ZDYzOTdmY2IwNDc3NDJiMWQ3YWI3MmJkOTczMSIsImNhbGxiYWNrIjoie1wiZm9ybWRhdGFcIjp7XCJhY3Rpb25cIjpcImh0dHA6Ly9wcm9kdWN0aW9uLmZyb250ZW5kLnNlcnZpY2UuZXUtd2VzdC0xLnd0OjMwMDAvYXBpL2JhY2tlbmQvdHJhbnNmZXJzLzFkNzQ3YzVjN2I0MzY0MDdmM2Y4ODZjNjc5MzJiNzYxMjAxOTA1MDUyMTE5MzgvZG93bmxvYWRzLzYxNjg0NjA1MzgvY29tcGxldGVkXCJ9LFwiZm9ybVwiOntcInN0YXR1c1wiOltcInBhcmFtXCIsXCJzdGF0dXNcIl0sXCJkb3dubG9hZF9pZFwiOlwiNjE2ODQ2MDUzOFwifX0ifQ.fSkUyCaLwSjHxQ0OffAmsHyd9O9etC_eY2_0Vj8iGv0`

 **Code used:**

```
r = await requests.get(url, allow_redirects=True, verify=False, stream=True)

if(r.status_code < 400):

    async with aiofiles.open(filename, mode='wb') as fd:
                                
        async for chunk in r.iter_content(chunk_size=8*1024):
                                    
            await fd.write(chunk)
```

**Error traceback:**

```
Traceback (most recent call last):

   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/adapters.py", line 54, in send

     timeout=timeout,

   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/pool.py", line 78, in request

     response = await connection.send(request)

   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/connections.py", line 76, in send

     status_code=status_code, reason=reason, headers=headers, body=body, on_close=self._release

   File "/app/.heroku/python/lib/python3.7/site-packages/httpcore/datastructures.py", line 149, in __init__

     decoder_cls = SUPPORTED_DECODERS[part]

 KeyError: b'none'

 

 During handling of the above exception, another exception occurred:

 

 Traceback (most recent call last):

   File "/app/downloads.py", line 109, in down_File

     r = await requests.get(url, allow_redirects=True, verify=False, stream=True)

   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/api.py", line 11, in get

     return await request("get", url, params=params, **kwargs)

   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/api.py", line 6, in request

     return await session.request(method=method, url=url, **kwargs)

   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/sessions.py", line 79, in request

     resp = await self.send(prep, **send_kwargs)

   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/sessions.py", line 136, in send

     r = await adapter.send(request, **kwargs)

   File "/app/.heroku/python/lib/python3.7/site-packages/requests_async/adapters.py", line 56, in send

     except (httpcore.BadResponse, socket.error) as err:

 NameError: name 'socket' is not defined
```

**Comment by Hanaasagi** [comment]
It was fixed in release 0.4.1 https://github.com/encode/requests-async/pull/45/files#diff-4f2c86eef5342546a715614d9dbbf5c9L56
