### ISSUE TITLE
Strange behaviour on request of specific URL

### ISSUE THREAD

**Issue by HarrySky** [encode/requests-async#52]
Using Python 3.7 I can send any request with timeout to any website and get expected ConnectTimeout or it will finish (you can replace 'https://spotify.com/' URL with anything):

```
>>> asyncio.run(requests_async.get('https://spotify.com/', timeout=0.1))
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/concurrency.py", line 149, in connect
    timeout.connect_timeout,
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/adapters.py", line 56, in send
    timeout=timeout,
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/interfaces.py", line 51, in request
    response = await self.send(request, stream=stream, ssl=ssl, timeout=timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 119, in send
    raise exc
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 114, in send
    request, stream=stream, ssl=ssl, timeout=timeout
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection.py", line 49, in send
    await self.connect(ssl=ssl, timeout=timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection.py", line 81, in connect
    host, port, ssl_context, timeout
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/concurrency.py", line 152, in connect
    raise ConnectTimeout()
httpcore.exceptions.ConnectTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/adapters.py", line 61, in send
    raise ConnectTimeout(err, request=request)
requests.exceptions.ConnectTimeout

Original exception was:
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/concurrency.py", line 149, in connect
    timeout.connect_timeout,
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/adapters.py", line 56, in send
    timeout=timeout,
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/interfaces.py", line 51, in request
    response = await self.send(request, stream=stream, ssl=ssl, timeout=timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 119, in send
    raise exc
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 114, in send
    request, stream=stream, ssl=ssl, timeout=timeout
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection.py", line 49, in send
    await self.connect(ssl=ssl, timeout=timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection.py", line 81, in connect
    host, port, ssl_context, timeout
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/concurrency.py", line 152, in connect
    raise ConnectTimeout()
httpcore.exceptions.ConnectTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/adapters.py", line 61, in send
    raise ConnectTimeout(err, request=request)
requests.exceptions.ConnectTimeout
```

But for some reason I get different error when trying to access **api.spotify.com** with timeout (any timeout - 1, 10, 50 seconds). And it hangs indefinitely if no timeout is provided.

```
>>> asyncio.run(requests_async.get('https://api.spotify.com/v1/me', timeout=0.1))
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/concurrency.py", line 65, in read
    self.stream_reader.read(n), timeout.read_timeout
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 114, in send
    request, stream=stream, ssl=ssl, timeout=timeout
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection.py", line 53, in send
    request, stream=stream, timeout=timeout
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/http2.py", line 77, in send
    await response.read()
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/models.py", line 684, in read
    self._content = b"".join([part async for part in self.stream()])
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/models.py", line 684, in <listcomp>
    self._content = b"".join([part async for part in self.stream()])
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/models.py", line 695, in stream
    async for chunk in self.raw():
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/models.py", line 712, in raw
    async for part in self._raw_stream:
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/http2.py", line 121, in body_iter
    event = await self.receive_event(stream_id, timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/http2.py", line 131, in receive_event
    data = await self.reader.read(self.READ_NUM_BYTES, timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/concurrency.py", line 68, in read
    raise ReadTimeout()
httpcore.exceptions.ReadTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/adapters.py", line 56, in send
    timeout=timeout,
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/interfaces.py", line 51, in request
    response = await self.send(request, stream=stream, ssl=ssl, timeout=timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 117, in send
    self.active_connections.remove(connection)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 64, in remove
    del self.all[connection]
KeyError: <httpcore.dispatch.connection.HTTPConnection object at 0x7f0e940d1a20>

Original exception was:
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/concurrency.py", line 65, in read
    self.stream_reader.read(n), timeout.read_timeout
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 114, in send
    request, stream=stream, ssl=ssl, timeout=timeout
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection.py", line 53, in send
    request, stream=stream, timeout=timeout
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/http2.py", line 77, in send
    await response.read()
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/models.py", line 684, in read
    self._content = b"".join([part async for part in self.stream()])
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/models.py", line 684, in <listcomp>
    self._content = b"".join([part async for part in self.stream()])
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/models.py", line 695, in stream
    async for chunk in self.raw():
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/models.py", line 712, in raw
    async for part in self._raw_stream:
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/http2.py", line 121, in body_iter
    event = await self.receive_event(stream_id, timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/http2.py", line 131, in receive_event
    data = await self.reader.read(self.READ_NUM_BYTES, timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/concurrency.py", line 68, in read
    raise ReadTimeout()
httpcore.exceptions.ReadTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "/home/harry/.local/lib/python3.7/site-packages/requests_async/adapters.py", line 56, in send
    timeout=timeout,
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/interfaces.py", line 51, in request
    response = await self.send(request, stream=stream, ssl=ssl, timeout=timeout)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 117, in send
    self.active_connections.remove(connection)
  File "/home/harry/.local/lib/python3.7/site-packages/httpcore/dispatch/connection_pool.py", line 64, in remove
    del self.all[connection]
KeyError: <httpcore.dispatch.connection.HTTPConnection object at 0x7f0e940d1a20>
```

I get KeyError when trying to delete connection as if **it does not even create a connection**. That's strange. Maybe you have idea why that might happen? I don't have this problem with `requests` package, but it is not async and I really want to use your great wrapper package.

**Comment by HarrySky** [comment]
How to reproduce in Python 3.7:
```
import asyncio
import requests_async
asyncio.run(requests_async.get('https://api.spotify.com/v1/me', timeout=0.1))
```

**Comment by HarrySky** [comment]
It works on 3.6 though. Checked with IPython. On Python 3.6 IPython it works, but if I use 3.7 - it hangs or throws the same KeyError.

How to reproduce with IPython:
```
import requests_async
await requests_async.get('https://api.spotify.com/v1/me', timeout=0.1)
```

**Comment by HarrySky** [comment]
It does not work with just Python 3.6 (without IPython) :(

**EDIT:** It works. Only Python 3.7 gives me KeyError.

How to reproduce in Python 3.6:
```
import asyncio
import requests_async

loop = asyncio.get_event_loop()
loop.run_until_complete(requests_async.get('https://api.spotify.com/v1/me', timeout=0.1))
loop.close()
```

Am I the only one experiencing problems with this or can you reproduce it as well?
Other domains work perfectly, `wget`, `curl` and original `requests` do not have problem with api.spotify.com

**Comment by HarrySky** [comment]
Moved to http3

**Comment by lovelydinosaur** [comment]
"Moved to http3" - Ace. I'll need to think about at what point to start recommending http3 instead.
~We don't yet have multipart support there is one possible blocker.~ (Also proxy support and .netrc, but those are lesser issues)  **Edit: We haz multipart uploads now.**

Anything obvious that you'd see as an issue in being able to switch to http3?

**Comment by HarrySky** [comment]
@tomchristie The only issue I had is with timeouts. I used requests tuple for timeout (ex. `(0.5, 0.25)`) and got this error:

```
  File "/usr/local/lib/python3.7/site-packages/http3/config.py", line 142, in __init__
    self.write_timeout = timeout[2]
IndexError: tuple index out of range
```

Maybe there should be a reminder that timeout does not work exactly like in requests.

Other than that - http3 is great :) And I don't experience issue with requests to api.spotify.com.

**Comment by lovelydinosaur** [comment]
Gotcha. Currently it’ll accept floats or 3-tuples (connect, read, write) timeouts.
